name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.GH_ACTIONS_SECRET }}" \
            -d '{
                  "ref": "${{ github.ref }}",
                  "repository": "${{ github.repository }}"
                }' \
            https://github-webhook.soyd.in
